# Generated by Django 4.1.7 on 2023-04-11 19:51

import FrameworkApp.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('instagram', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('bio', models.TextField(max_length=500)),
                ('age', models.IntegerField()),
                ('mobile_number', models.PositiveBigIntegerField()),
                ('mobile_number_verified', models.BooleanField(default=False)),
                ('photo_verified', models.BooleanField(default=False)),
                ('height', models.FloatField()),
                ('sexuality', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], default='M', max_length=1)),
                ('purpose', models.CharField(choices=[('C', 'Chat'), ('F', 'Friendship'), ('D', 'Date'), ('R', 'Relationship')], default='C', max_length=1)),
                ('activity_interests', models.CharField(choices=[('R', 'Running'), ('C', 'Cycling'), ('D', 'Dancing'), ('S', 'Singing')], default='R', max_length=1)),
                ('profile_interest', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender'), ('MF', 'Male and Female Both')], default='MF', max_length=2)),
                ('children', models.CharField(choices=[('DWT', "Don't wanna tell")], default='DWT', max_length=3)),
                ('drinking', models.CharField(choices=[('NVR', 'Never had never will'), ('OCC', 'Occationally')], default='NVR', max_length=3)),
                ('smoking', models.CharField(choices=[('NVR', 'Never had never will'), ('OCC', 'Occationally')], default='NVR', max_length=3)),
                ('languages', models.CharField(choices=[('HINDI', 'Hindi'), ('ENGLISH', 'English')], default='HINDI', max_length=20)),
                ('relationship_status', models.CharField(choices=[('S', 'Single'), ('E', 'Engaged'), ('M', 'Married'), ('D', 'Devorced')], default='S', max_length=1)),
                ('start_sign', models.CharField(choices=[('LIB', 'Libra')], default='LIB', max_length=3)),
                ('pets', models.CharField(choices=[('N', 'Not interested'), ('D', 'Dog lover'), ('C', 'Cat lover')], default='N', max_length=1)),
                ('religion', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('HINDU', 'Hindu'), ('MUSLIM', 'Muslim'), ('OTHER', 'Other')], default='NOT_STARTED', max_length=20)),
                ('personality', models.CharField(choices=[('I', 'Introvert'), ('E', 'Extrovert'), ('A', 'Ambivert')], default='I', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(height_field='image1_height', upload_to=FrameworkApp.models.user_images, width_field='image1_width')),
                ('image2', models.ImageField(height_field='image2_height', upload_to=FrameworkApp.models.user_images, width_field='image2_width')),
                ('image3', models.ImageField(height_field='image3_height', upload_to=FrameworkApp.models.user_images, width_field='image3_width')),
                ('image4', models.ImageField(height_field='image4_height', upload_to=FrameworkApp.models.user_images, width_field='image4_width')),
                ('image5', models.ImageField(height_field='image5_height', upload_to=FrameworkApp.models.user_images, width_field='image5_width')),
                ('image6', models.ImageField(height_field='image6_height', upload_to=FrameworkApp.models.user_images, width_field='image6_width')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.PositiveIntegerField(default=250)),
                ('visibility_area', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('likes_given', models.ManyToManyField(related_name='given', to='FrameworkApp.profile')),
                ('likes_recieved', models.ManyToManyField(related_name='recieved', to='FrameworkApp.profile')),
                ('personal_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FrameworkApp.personalinformation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FrameworkApp.appuser')),
            ],
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FrameworkApp.profileimages'),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FrameworkApp.profession'),
        ),
    ]
